# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Python image with uv pre-installed
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS uv

# Set the working directory
WORKDIR /app

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Copy the uv.lock and pyproject.toml files for dependency installation
COPY pyproject.toml uv.lock ./

# Install the project's dependencies using the lockfile and settings
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-install-project --no-dev --no-editable

# Copy the entire project into the /app directory
ADD . /app

# Install the project itself
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-dev --no-editable

# Expose the default MCP port
EXPOSE 5173

# Set the environment variable for the Brave API key
# This should be overridden with a secure key when running the container
ENV BRAVE_API_KEY=YOUR_API_KEY_HERE

# Use uv to run the MCP server
ENTRYPOINT ["uv", "run", "--with", "fastmcp", "--with", "python-dotenv", "--with", "beautifulsoup4", "--with", "requests", "fastmcp", "run", "mcp2brave.py"]
